[build]
  command = "pnpm install && pnpm turbo build"
  publish = "packages/api/dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  PNPM_FLAGS = "--no-frozen-lockfile"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 