name: Manual Deploy to GitHub Pages

on:
  # Runs only when manually triggered
  workflow_dispatch:
  # Runs on specific path changes
  push:
    branches: ["master"]
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - 'package.json'
      - 'vite.config.ts'
      - '.github/workflows/**'

permissions:
  contents: read
  pages: write
  id-token: write
  actions: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master  # Explicitly checkout master branch

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Clean install dependencies
        run: |
          rm -rf node_modules
          rm -rf dist
          npm ci

      - name: Build
        run: |
          npm run build
        env:
          VITE_BASE_URL: '/dte'
          NODE_ENV: 'production'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          timeout: 600000  # 10 minutes
          error_count: 10  # Number of retries
